name: chat_composer
description: A Flutter package for easy implementation of chat composer allows users to chat with Text, Audio, and Other Media.
version: 1.0.2
homepage: https://github.com/anokabb/chat_composer

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  fluttertoast: ^8.0.9
  path_provider: ^2.0.11
  flutter_sound_lite: ^8.5.0
  permission_handler: ^10.0.0
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - packages/chat_composer/images/delete_icon.png
